#spring.application.name=aboard

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bootex
    username: bootuser
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  thymeleaf:
    cache: false

mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.atest.aboard.domain

logging:
  level:
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security: DEBUG

